# Student ID: 123456780

**You student_id is your 7/8 digit faser number.**

This is a sample format for CE807: Assignment . You must follow the format.
The code will have three broad sections, and additional section, if needed,


1.   Common Codes
2.   Method/model 1 Specific Codes
3.   Method/model 2 Specific Codes
4.   Other Method/model Codes, if any

**You must have `train_unsup`, `test_unsup` for Unsupervised method  and `train_dis`, `test_dis` for Discriminatuve method to perform full training and testing. This will be evaluated automatically, without this your code will fail and no marked.**

You code should be proverly indended, print as much as possible, follow standard coding (https://peps.python.org/pep-0008/) and documentaion (https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.01-Help-And-Documentation.ipynb) practices.

Before each `code block/function`, you must have a `text block` which explain what code block/function is going to do. For each function/class, you need to properly document what are it's input, functionality and output.

If you are using any non-standard library, you must have command to install that, for example `pip install datasets`.

You must print `train`, `validation` and `test` performance measures.

You must also print `train` and `validation` loss in each `epoch`, wherever you are using `epoch`, say in any deep learning algorithms.

Your code must

*   To reproducibality of the results you must use a `seed`, you have to set seed in `torch`, `numpy` etc, use same seed everywhere **and your Student ID should be your seed**.
*   read dataset from './data/number/', where number is last digit of your student_id folder which will have 3 files [`train.csv`, `val.csv`, `test.csv`]
*   save model after finishing the training in './model/student_id/Model_Unsup/' and './model/student_id/Model_Dis/' for Unsupervised and Discriminative model respectively.
*   at testing time you will load models from './model/student_id/Model_Unsup/' and './model/student_id/Model_Dis/'  for Unsupervised and Discriminative model respectively. Your output file based on the test file will be named “test.csv” and you will add/modify “out_label_model_unsup” and “out_label_model_dis” column in the existing columns from test.csv. These outputs will be generated from your trained models.
*  after testing, your output file will be named “test.csv” and you will add/modify “out_label_model_unsup” and “out_label_model_Dis” column in the existing columns from test.csv. These outputs will be generated from your trained models.




**Install and import all required libraries first before starting to code.**

Let's install all require libraries. For example, `transformers`

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.27.1-py3-none-any.whl (6.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 46.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from transformers) (23.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.9/dist-packages (from transformers) (4.65.0)
Collecting huggingface-hub<1.0,>=0.11.0
  Downloading huggingface_hub-0.13.2-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 20.1 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from transformers) (2.25.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 43.1 MB/s eta 0:00:00
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from transformers) (6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from transformers) (3.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.5.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (1.26.15)
Installing collected packages: tokenizers, huggingface-hub, transformers
Successfully installed huggingface-hub-0.13.2 tokenizers-0.13.2 transformers-4.27.1

Let's import all require libraries.
For example, `numpy`

In [ ]:
import numpy as np
import os
import pickle
import pandas as pd

**Let's put your student id as a variable, that you will use different places**

In [ ]:
student_id = 12345670 # Note this is an interger and you need to input your id

Let's set `seed` for all libraries like `torch`, `numpy` etc as my student id

In [ ]:
# set same seeds for all libraries

#numpy seed
np.random.seed(student_id)

train_unsup()
test_unsup()
train_dis()
test_dis()

# Common Codes

In this section you will write all common codes, for examples


*   Data read
*   Command Line argument reading
*   Performance Matrics
*   Print Dataset Statistics
*   Saving model and output
*   Loading Model and output
*   etc

**Let's first allow the GDrive access and set data and model paths**

For examples,

student_id = 12345670

set GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = ‘./CE807-25-SP/Assignment/’ in your GDrive

now set all global variable,


Sample output directory and file structure:

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [ ]:
# Add your code to initialize GDrive and data and models paths

GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = './CE807-26-SP/Assignment/'
GOOGLE_DRIVE_PATH = os.path.join('gdrive', 'MyDrive', GOOGLE_DRIVE_PATH_AFTER_MYDRIVE)
print('List files: ', os.listdir(GOOGLE_DRIVE_PATH))

List files:  ['code.ipynb', 'model', 'data', 'CE807-SP-Dataset.zip']

In [ ]:
DATA_PATH = os.path.join(GOOGLE_DRIVE_PATH, 'data', '0') # Make sure to replace 0 with your data id
train_file = os.path.join(DATA_PATH, 'train.csv')
print('Train file: ', train_file)

val_file = os.path.join(DATA_PATH, 'valid.csv')
print('Validation file: ', val_file)

test_file = os.path.join(DATA_PATH, 'test.csv')
print('Test file: ', test_file)

Train file:  gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/train.csv
Validation file:  gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/valid.csv
Test file:  gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/test.csv

In [ ]:
# Read train Data
train_df = pd.read_csv(train_file)
train_df.head()

       id  data_id                                               text  rating
0    7136        0  Holds plenty of water to keep house humidity u...       5
1  474092        0  I use this brand all the time now and will in ...       5
2  383218        0  Was an exact replacement for the old one. easy...       5
3  101515        0  It's dead after 5 months. Stay away from those...       1
4  342116        0       Easy to change out for do-it-yourselfers !!!       5

In [ ]:
# Read Validation Data
val_df = pd.read_csv(val_file)
val_df.head()

       id  data_id                                               text  rating
0  219740        0  These arrived in perfect condition. I have had...       5
1  299133        0  Quick delivery, everything as promised. Thank ...       5
2  159188        0  Love ❤️ it very easy to remove and replace. Do...       5
3  421203        0  Easy to install.  Worked immediately.<br /><br...       5
4  659721        0  Put the drum rollers in our Samsung dryer 2 mo...       1

In [ ]:
# Read Test Data
test_df = pd.read_csv(test_file)
test_df.head()

,id,data_id,text,out_label_model_1,out_label_model_2
0,604369,0,I will be back for more :),NaN,NaN
1,159123,0,Great replacement for the broken ice maker. W...,NaN,NaN
2,197585,0,These came very quickly in the mail. They are ...,NaN,NaN
3,326380,0,We installed this because the rollers broke on...,NaN,NaN
4,524147,0,I installed this burner and it’s been working ...,NaN,NaN

In [ ]:
# taken from Lab 09
def read_data(file_name):
  df = pd.read_csv(file_name)
  print(file_name, 'has', len(df),'data points')
  return df

In [ ]:
test_df = read_data(test_file)

gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/test.csv has 1386 data points

In [ ]:
MODEL_PATH = os.path.join(GOOGLE_DRIVE_PATH, 'model', str(student_id)) # Make sure to use your student Regitration number
MODEL_Dis_DIRECTORY = os.path.join(MODEL_PATH, 'model_dis') # Model Discriminative directory
print('Model Generative directory: ', MODEL_Dis_DIRECTORY)

MODEL_unsup_DIRECTORY = os.path.join(MODEL_PATH, 'model_unsup') # Model unsuper directory
print('Model Unsuper directory: ', MODEL_unsup_DIRECTORY)

os.makedirs(MODEL_Dis_DIRECTORY, exist_ok=True)
os.makedirs(MODEL_unsup_DIRECTORY, exist_ok=True)

Model Generative directory:  gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_dis
Model Unsuper directory:  gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_unsup

# Method Unsupervised Start

In this section you will write all details of your Method 1.

You will have to enter multiple `code` and `text` cell.

Your code should follow the standard ML pipeline


*   Data reading
*   Data clearning, if any
*   Convert data to vector/tokenization/vectorization
*   Model Declaration/Initialization/building
*   Training and validation of the model using training and validation dataset
*   Save the trained model
*   Load and Test the model on testing set
*   Save the output of the model


You could add any other step(s) based on your method's requirement.

After finishing the above, you need to usd splited data as defined in the assignment and then do the same for all 4 sets. Your code should not be copy-pasted 4 time, make use of `function`.

In [ ]:
# Your Code(s)

## Training Unsupervised Method Code
Your test code should be a stand alone code that must take `train_file`, `val_file`,  and `model_dir` as input. You could have other things as also input, but these three are must. You would load both files, and train using the `train_file` and validating using the `val_file`. You will `print` / `display`/ `plot` all performance metrics, loss(if available) and save the output model in the `model_dir`.

Note that at the testing time, you need to use the same pre-processing and model. So, it would be good that you make those as seperate function/pipeline whichever it the best suited for your method. Don't copy-paste same code twice, make it a fucntion/class whichever is best.

In [ ]:
# Your Code(s)

## Testing Method Unsupervised Code
Your test code should be a stand alone code that must take `test_file`, `model_file` and `output_dir` as input. You could have other things as also input, but these three are must. You would load both files, and generate output based on inputs. Then you will `print` / `display`/ `plot` all performance metrics, and save the output file in the `output_dir`

In [ ]:
# Your Code(s)

## Method Unsupervised End

# Method Discriminative Start

In this section you will write all details of your Method 2.

You will have to enter multiple `code` and `text` cell.

Your code should follow the standard ML pipeline


*   Data reading
*   Data clearning, if any
*   Convert data to vector/tokenization/vectorization
*   Model Declaration/Initialization/building
*   Training and validation of the model using training and validation dataset
*   Save the trained model
*   Load and Test the model on testing set
*   Save the output of the model

You could add any other step(s) based on your method's requirement.

After finishing the above, you need to usd splited data as defined in the assignment and then do the same for all 4 sets. Your code should not be copy-pasted 4 time, make use of `function`.

In [ ]:
# Your Code(s)

## Training Method Discriminative Code
Your test code should be a stand alone code that must take `train_file`, `val_file`,  and `model_dir` as input. You could have other things as also input, but these three are must. You would load both files, and train using the `train_file` and validating using the `val_file`. You will `print` / `display`/ `plot` all performance metrics, loss(if available) and save the output model in the `model_dir`.

Note that at the testing time, you need to use the same pre-processing and model. So, it would be good that you make those as seperate function/pipeline whichever it the best suited for your method. Don't copy-paste same code twice, make it a fucntion/class whichever is best.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, f1_score

In [ ]:
def train_Gen(train_file, val_file, model_dir):
    """
    Takes train_file, val_file and model_dir as input.
    It trained on the train_file datapoints, and validate on the val_file datapoints.
    While training and validating, it print different evaluataion metrics and losses, wheverever necessary.
    After finishing the training, it saved the best model in the model_dir.

    ADD Other arguments, if needed.

    Args:
        train_file: Train file name
        val_file: Validation file name
        model_dir: Model output Directory



    """

    ##########################################################################
    #                     TODO: Implement this function                      #
    ##########################################################################
    # Replace "pass" statement with your code

    # Read training and validation set data
    train_df = pd.read_csv(train_file)
    val_df = pd.read_csv(val_file)
    print('Training set has', len(train_df),'data points')
    print('Validation set has', len(val_df),'data points')

    train_data = train_df.sample(frac=0.1).reset_index(drop=True) # Shuffling and selecting 10% of data



    # Create vocabulary using count vectorizer
    count_vectorizer = CountVectorizer() # Note no pre-processing is done here. In practice you will have different preprocessing steps.
    counts = count_vectorizer.fit_transform(train_data['text'].values)

    # NB classifier
    classifier = MultinomialNB()
    targets = train_data['sentiment'].values

    #train the classifier
    print('Start training')
    classifier.fit(counts, targets)
    print('Done training')

    model_file = os.path.join(model_dir, 'model.sav')
    pickle.dump(classifier, open(model_file, 'wb'))
    print('Saved model to', model_file)

    vocab_file = os.path.join(model_dir, 'vocab.sav')
    pickle.dump(count_vectorizer, open(vocab_file, 'wb'))
    print('Saved vocab to', vocab_file)

    # Testing on the validation data
    val_counts=count_vectorizer.transform(val_df['text'])
    predictions= classifier.predict(val_counts)
    print('Validation Done')
    target  = val_df['sentiment']

    score=f1_score(target, predictions, average='macro')

    print('macro F1 Score on Validation set', score)
    ##########################################################################
    #                            END OF YOUR CODE                            #
    ##########################################################################
    return

In [ ]:
train_Gen(train_file, val_file, MODEL_Dis_DIRECTORY)

Training set has 4914 data points
Validation set has 700 data points
Start training
Done training
Saved model to gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_dis/model.sav
Saved vocab to gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_dis/vocab.sav
Validation Done
macro F1 Score on Validation set 0.21754760576846466

In [ ]:
def test_Gen(test_file, model_dir):
    """
    Takes train_file, val_file and model_dir as input.
    It trained on the train_file datapoints, and validate on the val_file datapoints.
    While training and validating, it print different evaluataion metrics and losses, wheverever necessary.
    After finishing the training, it saved the best model in the model_dir.

    ADD Other arguments, if needed.

    Args:
        train_file: Train file name
        val_file: Validation file name
        model_dir: Model output Directory



    """

    ##########################################################################
    #                     TODO: Implement this function                      #
    ##########################################################################
    # Replace "pass" statement with your code

    # Read training and validation set data
    # test_df = pd.read_csv(test_file)
    # print('Testing set has', len(test_df),'data points')

    test_df = read_data(test_file)
    print('Testing set has', len(test_df),'data points')


    model_file = model_dir +'/model.sav'
    classifier = pickle.load(open(model_file, 'rb'))
    print('Model loaded from', model_file)

    vocab_file = model_dir +'/vocab.sav'
    count_vectorizer = pickle.load(open(vocab_file, 'rb'))
    print('Vocab loaded from ', vocab_file )

    # Testing on the test data
    test_counts=count_vectorizer.transform(test_df['text'])
    predictions= classifier.predict(test_counts)
    print('Testing Done')
    # target  = test_df['sentiment']

    # score=f1_score(target, predictions, average='macro')

    # print('macro F1 Score on Test set', score)

    test_df['out_label_model_1'] = predictions

    test_df.to_csv(test_file,index=False)
    print('Saved output to ',test_file)

    ##########################################################################
    #                            END OF YOUR CODE                            #
    ##########################################################################

In [ ]:
test_Gen(test_file, MODEL_Dis_DIRECTORY)

gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/test.csv has 1386 data points
Testing set has 1386 data points
Model loaded from gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_dis/model.sav
Vocab loaded from  gdrive/MyDrive/./CE807-26-SP/Assignment/model/12345670/model_dis/vocab.sav
Testing Done
Saved output to  gdrive/MyDrive/./CE807-26-SP/Assignment/data/0/test.csv

## Testing Method Discriminative Code
Your test code should be a stand alone code that must take `test_file`, `model_file` and `output_dir` as input. You could have other things as also input, but these three are must. You would load both files, and generate output based on inputs. Then you will `print` / `display`/ `plot` all performance metrics, and save the output file in the `output_dir`

In [ ]:
# Your Code(s)

## Discriminative Method  End

# Other Method/model Start

In [ ]:
# Your Code(s)

##Other Method/model End